import type { DePINNetwork } from "./depin-types"

// List of EVM-compatible DePIN networks that can be mined through physical activities
export const EVMDePINNetworks: DePINNetwork[] = [
  {
    id: "sweatcoin",
    name: "Sweatcoin",
    tokenSymbol: "SWEAT",
    tokenName: "Sweat Economy",
    logoUrl: "/sweatcoin-inspired-logo.png",
    description: "Move-to-earn token rewarding physical activity",
    enabled: false,
  },
  {
    id: "stepn",
    name: "STEPN",
    tokenSymbol: "GMT",
    tokenName: "Green Metaverse Token",
    logoUrl: "/stepn-logo-generic.png",
    description: "Move-to-earn NFT game with EVM compatibility",
    enabled: false,
  },
  {
    id: "walken",
    name: "Walken",
    tokenSymbol: "WLKN",
    tokenName: "Walken Token",
    logoUrl: "/walken-logo.png",
    description: "Move-to-earn game with step tracking",
    enabled: false,
  },
  {
    id: "genopets",
    name: "Genopets",
    tokenSymbol: "GENE",
    tokenName: "Genopets Token",
    logoUrl: "/genopets-inspired-logo.png",
    description: "Move-to-earn game with genetic evolution mechanics",
    enabled: false,
  },
  {
    id: "dotmoovs",
    name: "dotmoovs",
    tokenSymbol: "MOOV",
    tokenName: "dotmoovs Token",
    logoUrl: "/dotmoovs-logo.png",
    description: "AI-powered sports challenges with blockchain rewards",
    enabled: false,
  },
  {
    id: "fitmint",
    name: "Fitmint",
    tokenSymbol: "FITT",
    tokenName: "Fitmint Token",
    logoUrl: "/placeholder.svg?height=200&width=200&query=fitmint logo",
    description: "Move-to-earn fitness app with EVM compatibility",
    enabled: false,
  },
  {
    id: "iotex",
    name: "IoTeX",
    tokenSymbol: "IOTX",
    tokenName: "IoTeX Token",
    logoUrl: "/placeholder.svg?height=200&width=200&query=iotex logo",
    description: "EVM-compatible blockchain for IoT devices",
    enabled: false,
  },
  {
    id: "metaverse",
    name: "Metaverse",
    tokenSymbol: "MV",
    tokenName: "Metaverse Token",
    logoUrl: "/placeholder.svg?height=200&width=200&query=metaverse logo",
    description: "Blockchain for digital identity and assets",
    enabled: false,
  },
  {
    id: "playtoearn",
    name: "PlayToEarn",
    tokenSymbol: "P2E",
    tokenName: "PlayToEarn Token",
    logoUrl: "/placeholder.svg?height=200&width=200&query=playtoearn logo",
    description: "Gaming rewards on EVM chains",
    enabled: false,
  },
]
